runtime: php55
api_version: 1

handlers:
- url: /styles
  static_dir: styles

- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /
  script: index.php
  secure: always

- url: /(.+\.php)$
  script: \1
  secure: always
